### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by egoarka** [benji6/church#1]
Hello, tried your lib and it's awesome. But one of the disadvantages of this lib is lack of definitions. Do you want to implement TypeScript definitions? It would be great.

**Comment by geopic** [comment]
Hello @benji6. If you ever need someone to write a TS definitions file for you, I have all the time in the world to do it. Saves you from having to rewrite the whole library, just saying. 😉

**Comment by benji6** [comment]
Well it seems I didn't get round to rewriting this in TypeScript since my comment back in August 2018! Thank you for the offer @geopic, let me have a look over the next week to see how feasible a conversion to TS would be, if it seems like too much effort then I'll let you know and you'd be very welcome to write some definitions

**Comment by benji6** [comment]
Alright I've had a look at this. Basically I don't have a very strong apetite for rewriting in TypeScript.

My reasons are:

### Source code is a lot noisier

We can look at the successor function (`succ`) to illustrate this point. It is a bit subjective but I find the JavaScript a lot easier to read:

```js
const succ = a => b => c => a(b)(b(c))
```

than the TypeScript:

```ts
const succ = <A extends Function, B extends Function, C>(a: A) => (b: B) => (c: C) => a(b)(b(c))
```

### Type annotations are hard

We can look at the successor function (`succ`) again to illustrate this point:

```ts
const succ = <A extends Function, B extends Function, C>(a: A) => (b: B) => (c: C) => a(b)(b(c))
```
The first generic `A` is just defined as extending `Function` but truthfully the type of parameter `a` should be a Church encoded numeral, but I have no idea how to type a Church encoded numeral in TypeScript. It might be possible and am open to suggestions but beyond extending `Function` I can't think of much here.

### Sceptical about how useful types would be

I can't think of any reason why anyone would be seriously using this project so I'm sceptical of how useful types would be

___

Anyway, I'm not sure what others think about this, but if you still wanted to have a go at adding type definitions for this @geopic you would be very welcome, I'm just not sure how useful they would actually be. There are no dependent projects on this library https://github.com/benji6/church/network/dependents & https://www.npmjs.com/browse/depended/church - which I am pretty grateful for given that we should probably be using native JS numbers & arrays etc! 😄

**Comment by benji6** [comment]
I'm going to close this issue based on my last message, feel free to reopen if anyone wants to continue the discussion

**Comment by IRod22** [comment]
Implementing `.d.ts` is impossible unless Typescript allowed generic types as parameters, which would look like this:

```ts
type OfNumber<Wrapper> = Wrapper<number>

const arrayOfNums: OfNumber<Array> = [1, 2, 3]
```

That example would not compile. For something to compare the TS code above to, the example above in Haskell would look similar to this:

```hs
type OfInt wrapper = wrapper Int

arrayOfInts:: OfInt []
arrayOfInts = [1, 2, 3] 
```

I saw an RFC for generic types as parameters, but I cannot find it anymore. :(
